[project]
name = "foodloop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.5.9",
    "langchain>=1.4.3",
    "langchain-chroma>=1.1.0",
    "langchain-openai>=1.6.7",
    "langgraph>=1.2.14",
    "openai>=3.26.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.4",
    "sounddevice>=0.5.6",
    "soundfile>=0.14.0",
]
